import type { NextPage } from 'next'
import Head from 'next/head'
import { signIn, signOut, useSession } from 'next-auth/react'
import { trpc } from '../utils/trpc'
import { Layout } from '../layouts/Layout'

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: 'from tRPC' })

  return (
    <>
      <Head>
        <title>ZKP</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className="container flex flex-col items-center justify-center min-h-screen p-4 mx-auto">
          <h1>A Thesis</h1>
        </main>
      </Layout>
    </>
  )
}

export default Home
